---
- hosts: all
  tasks:
        - name: Creating a repository file for Kubernetes
          file:
            path: /etc/yum.repos.d/kubernetes.repo
            state: touch
        - name: Adding repository details in kubernetes repo file.
          blockinfile:
            path: /etc/yum.repos.d/kubernetes.repo
            block: |
                [kubernetes]
                name=Kubernetes
                baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
                enabled=1
                gpgcheck=1
                repo_gpgcheck=1
                gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

        - name: yum-makecache
          command: yum makecache -y
          args:
            warn: no

        - name: Disabling Swap on all nodes
          command: swapoff -a

        - name: Commenting Swap entries in /etc/fstab
          replace:
            path: /etc/fstab
            regexp: '(.*swap*)'
            replace: '#\1'

        - name: Install required system packages
          yum: name={{ item }}
          loop: [ 'kubeadm', 'kubectl', 'kubelet']

        - name: Create k8s.conf file
          file:
            path: /etc/sysctl.d/k8s.conf
            state: touch

        - name: Configure IP Tables
          blockinfile:
            path: /etc/sysctl.d/k8s.conf
            block: |
                net.bridge.bridge-nf-call-ip6tables = 1
                net.bridge.bridge-nf-call-iptables = 1

        - name: Disable firewalld
          service:
            name: firewalld
            enabled: false
            state: stopped

        - name: Disable selinux
          shell: |
            sed -i s/^SELINUX=.*$/SELINUX=permissive/ /etc/selinux/config
            setenforce=0
          args:
            warn: no

        - name: enable kubelet
          service:
                name: kubelet
                enabled: true
                state: started
