def gv
pipeline{
    agent any
    environment{
        NEW_VERSION = '1.3.0'
        SERVER_CREDENTIALS = credentials('ID')
    }
    
    tools{
        maven 'Maven'
    }

    parameters{
        string(name: 'VERSION', defaultValue: '', description: 'version to deploy on prod')
        choice(name: 'VERSION', choices: ['1.1.0', '1.2.0', '1.3.0'], description: '')
        booleanParam(name: 'executeTests', defaultValue: true, description: '')
    }

    stages{
        stage("build"){
            steps{
                echo  'building the application'
                echo "building version ${NEW_VERSION}"
                script{
                    //write groovy scripts
                    gv = load "script.groovy"
                }
            }
        }
            
        stage("test"){
            steps{
                echo 'testing the application'
                when{
                    expression{
                        params.executeTests
                    }
                }
            }
        }
            
        stage("deploy"){
            when {
                expression{
                    env.BRANCH_NAME == 'master' || env.BRANCH_NAME == 'dev'
                }
            }
            steps{
                echo 'deploying the application'
                echo "deploying version ${params.VERSION}"
            }
        }
    }
    post{
        always{
            echo 'always action'
        }
        success{
            echo 'action success'
        }
        failure{
            echo 'action failure'
        }
    }
}