- hosts: masters
  tasks:
        - name: Pulling images required for setting up a Kubernetes cluster
          shell: kubeadm config images pull

        - name: Initializing Kubernetes cluster
          shell: kubeadm init

        - name: Copying required files
          shell: |
           mkdir -p $HOME/.kube
           cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
           chown $(id -u):$(id -g) $HOME/.kube/config
          args:
            warn: no

        - name: Generate join command
          shell: kubeadm token create --print-join-command
          register: join_command

        - name: Copy join command to local file
          local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

        - name: Install Network Add-on
          command: kubectl apply -f https://cloud.weave.works/k8s/net
